export const roleCodes = {
  admin: 'hmsw-ADM-001',
  managingPartner: 'hmsw-MGNPTNR-002',
  associate: 'hmsw-ASS-003',
  paralegal: 'hmsw-PAL-004',
  client: 'hmsw-CLI-005',
};

export const roles = [
  { label: 'Admin', value: 'admin' },
  { label: 'Managing Partner', value: 'managingPartner' },
  { label: 'Senior Lawyer', value: 'seniorLawyer' },
  { label: 'Associate Lawyer', value: 'associate' },
  { label: 'Paralegal', value: 'paralegal' },
];

export const portalsLinks = {
  Dashboard: 'Dashboard',
  CaseManagement: 'case-management',
  ClientManagement: 'client-management',
  DocumentManagement: 'document-management',
  BillingAndFinance: 'billing-and-finances',
  Communication: 'Communication',
  TasksAndReminders: 'tasks-and-reminders',
  ReportsAndAnalytics: 'reports-and-analytics',
  UserManagement: 'user-management',
  Settings: 'settings',
  CaseStatus: 'case-status',
  Documents: 'documents',
};

export const rolesAndPermissions = {
  admin: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "User Management Overview",
      // "System Configuration Status",
      // "All Case Files Summary",
      // "Comprehensive Reports",
      // "System Activity Logs",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Full Access to All Case Files",
      // "User Management Tools",
      // "System Configuration Settings",
      // "Report Generation and Viewing",
      // "Audit and Activity Logs",

      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  managingPartner: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Firm-wide Case Overview",
      // "Financial Data and Performance",
      // "Case Progress Metrics",
      // "Team Permissions Overview",
      // "Case Assignment Status",

      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to All Case Files",
      // "Firm-wide Report Generation",
      // "Case Assignment Tools",
      // "Financial Data Access",
      // "Team Management Tools",

      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  seniorLawyer: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Case Status Updates",
      // "Client Communication Summary",
      // "Case Documentation Progress",
      // "Legal Research Tools Access",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Update Case Status",
      // "Manage Case Documentation",
      // "Client Communication Tools",
      // "Generate Case Reports",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  associate: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Case Status Updates",
      // "Client Communication Summary",
      // "Task List",
      // "Case Report Insights",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Update Case Status",
      // "Manage Case Documentation",
      // "Client Communication Tools",
      // "Generate Case Reports",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  paralegal: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Upcoming Deadlines",
      // "Document Preparation Tasks",
      // "Administrative Communication",
      // "Legal Research Tools Access",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Assist with Legal Documentation",
      // "Prepare Draft Documents",
      // "Administrative Communication Tools",
      // "Legal Research Resources",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
};
