export const roleCodes = {
  admin: 'hmsw-ADM-001',
  managingPartner: 'hmsw-MGNPTNR-002',
  associate: 'hmsw-ASS-003',
  paralegal: 'hmsw-PAL-004',
  client: 'hmsw-CLI-005',
};

export const roles = [
  // { label: 'Admin', value: 'admin' },
  { label: 'Managing Partner', value: 'managingPartner' },
  { label: 'Senior Lawyer', value: 'seniorLawyer' },
  { label: 'Associate Lawyer', value: 'associate' },
  { label: 'Paralegal', value: 'paralegal' },
  // { "label": "Legal Secretary", "value": "legalSecretary" },
  // { "label": "Billing Clerk", "value": "billingClerk" },
  // { "label": "Client Relationship Manager", "value": "clientRelationshipManager" },
  // { "label": "IT Support", "value": "itSupport" },
  // { "label": "Client (External)", "value": "clientExternal" }
];

export const portalsLinks = {
  Dashboard: 'Dashboard',
  CaseManagement: 'case-management',
  ClientManagement: 'client-management',
  DocumentManagement: 'document-management',
  BillingAndFinance: 'billing-and-finances',
  Communication: 'Communication',
  TasksAndReminders: 'tasks-and-reminders',
  ReportsAndAnalytics: 'reports-and-analytics',
  UserManagement: 'user-management',
  Settings: 'settings',
  CaseStatus: 'case-status',
  Documents: 'documents',
};

export const rolesAndPermissions = {
  admin: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "User Management Overview",
      // "System Configuration Status",
      // "All Case Files Summary",
      // "Comprehensive Reports",
      // "System Activity Logs",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Full Access to All Case Files",
      // "User Management Tools",
      // "System Configuration Settings",
      // "Report Generation and Viewing",
      // "Audit and Activity Logs",

      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  managingPartner: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Firm-wide Case Overview",
      // "Financial Data and Performance",
      // "Case Progress Metrics",
      // "Team Permissions Overview",
      // "Case Assignment Status",

      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to All Case Files",
      // "Firm-wide Report Generation",
      // "Case Assignment Tools",
      // "Financial Data Access",
      // "Team Management Tools",

      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  seniorLawyer: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Case Status Updates",
      // "Client Communication Summary",
      // "Case Documentation Progress",
      // "Legal Research Tools Access",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Update Case Status",
      // "Manage Case Documentation",
      // "Client Communication Tools",
      // "Generate Case Reports",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  associateLawyer: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Case Status Updates",
      // "Client Communication Summary",
      // "Task List",
      // "Case Report Insights",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Update Case Status",
      // "Manage Case Documentation",
      // "Client Communication Tools",
      // "Generate Case Reports",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  paralegal: {
    permissions: {
      Dashboard: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ClientManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      DocumentManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      BillingAndFinance: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Communication: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      TasksAndReminders: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      ReportsAndAnalytics: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      UserManagement: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Settings: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      CaseStatus: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
      Documents: [
        'full_access',
        'user_management',
        'access_all_case_files',
        'generate_view_all_reports',
        'system_configuration',
        'create_record',
        'read_record',
        'update_record',
        'delete_record',
      ],
    },
    dashboard: [
      // "Assigned Case List",
      // "Upcoming Deadlines",
      // "Document Preparation Tasks",
      // "Administrative Communication",
      // "Legal Research Tools Access",
      'Spending Summary',
      'New Case',
      'Active Cases',
      'Outstanding Tasks and Assignments',
      'Recent Activities',
      'Appointments',
      'Employees Reports',
      'Something Here',
      'Client Reports',
      'Pending Client Payment',
      'something',
      'Something Cases',
      'Recent Communication',
    ],
    portal: [
      // "Access to Assigned Case Files",
      // "Assist with Legal Documentation",
      // "Prepare Draft Documents",
      // "Administrative Communication Tools",
      // "Legal Research Resources",
      'Dashboard',
      'case-management',
      'client-management',
      'document-management',
      'billing-and-finances',
      'Communication',
      'tasks-and-reminders',
      'reports-and-analytics',
      'user-management',
      'settings',
      'case-status',
      'documents',
    ],
  },
  
  // "legalSecretary": {
  //   "permissions": [
  //     "access_assigned_case_files",
  //     "schedule_manage_appointments",
  //     "prepare_draft_legal_correspondence",
  //     "manage_administrative_tasks",
  //     "communicate_with_clients_scheduling"
  //   ],
  //   "dashboard": [
  //     "Scheduled Appointments",
  //     "Upcoming Deadlines",
  //     "Drafting and Correspondence Tasks",
  //     "Administrative Task Overview",
  //     "Client Communication Summary"
  //   ],
  //   "portal": [
  //     "Access to Case Files",
  //     "Appointment Scheduling Tools",
  //     "Draft Legal Correspondence",
  //     "Manage Administrative Tasks",
  //     "Client Communication Tools"
  //   ]
  // },
  // "billingClerk": {
  //   "permissions": [
  //     "access_billing_information",
  //     "generate_invoices",
  //     "manage_payments",
  //     "access_financial_reports",
  //     "communicate_with_clients_billing"
  //   ],
  //   "dashboard": [
  //     "Pending Invoices",
  //     "Payment Status Overview",
  //     "Financial Report Summary",
  //     "Client Billing Issues",
  //     "Upcoming Payment Deadlines"
  //   ],
  //   "portal": [
  //     "Access to Billing Information",
  //     "Invoice Generation Tools",
  //     "Payment Management System",
  //     "Generate Financial Reports",
  //     "Communicate with Clients About Billing"
  //   ]
  // },
  // "clientRelationshipManager": {
  //   "permissions": [
  //     "access_client_contact_information",
  //     "communicate_with_clients_progress",
  //     "generate_view_client_reports",
  //     "manage_client_engagement"
  //   ],
  //   "dashboard": [
  //     "Client List and Status",
  //     "Client Feedback and Communication",
  //     "Client Engagement Metrics",
  //     "Case Progress Updates",
  //     "Upcoming Meetings and Follow-ups"
  //   ],
  //   "portal": [
  //     "Access to Client Contact Information",
  //     "Track Case Progress",
  //     "Manage Client Communication",
  //     "Generate Client Reports",
  //     "Client Engagement Tools"
  //   ]
  // },
  // "iTSupport": {
  //   "permissions": [
  //     "access_system_configuration",
  //     "user_management",
  //     "monitor_system_performance",
  //     "access_user_activity_logs"
  //   ],
  //   "dashboard": [
  //     "System Performance Metrics",
  //     "User Access Logs",
  //     "Pending Support Tickets",
  //     "System Configuration Overview",
  //     "Security Alerts and Notifications"
  //   ],
  //   "portal": [
  //     "Access to System Configuration",
  //     "Manage User Accounts",
  //     "Monitor System Performance",
  //     "Review User Activity Logs",
  //     "Manage Support Tickets"
  //   ]
  // },
  // "clientExternal": {
  //   "permissions": [
  //     "access_own_case_information",
  //     "upload_documents",
  //     "communicate_with_legal_team",
  //     "view_invoices",
  //     "schedule_appointments"
  //   ],
  //   "dashboard": [
  //     "Case Status Overview",
  //     "Uploaded Documents",
  //     "Invoice Summary",
  //     "Scheduled Appointments",
  //     "Upcoming Deadlines"
  //   ],
  //   "portal": [
  //     "Access to Own Case Information",
  //     "Upload Documents",
  //     "Communicate with Legal Team",
  //     "View Invoices and Payment History",
  //     "Schedule and Manage Appointments"
  //   ]
  // }
};
